// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLO95ytkCv6LYvokTZL4x9a-6weUAIPMM',
    appId: '1:675335972613:web:3fb0c0de5094f8e83ab96c',
    messagingSenderId: '675335972613',
    projectId: 'avs-control',
    authDomain: 'avs-control.firebaseapp.com',
    databaseURL: 'https://avs-control-default-rtdb.firebaseio.com',
    storageBucket: 'avs-control.appspot.com',
    measurementId: 'G-63EVTECDBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMhCJw-h37LFRV5yW71uboMyejIZZSkEc',
    appId: '1:675335972613:android:fe4a95878dd15b0f3ab96c',
    messagingSenderId: '675335972613',
    projectId: 'avs-control',
    databaseURL: 'https://avs-control-default-rtdb.firebaseio.com',
    storageBucket: 'avs-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFYea0bkcGUaGa8_TOD7ACKTio1QJAI0',
    appId: '1:675335972613:ios:47505aa129d4cbd33ab96c',
    messagingSenderId: '675335972613',
    projectId: 'avs-control',
    databaseURL: 'https://avs-control-default-rtdb.firebaseio.com',
    storageBucket: 'avs-control.appspot.com',
    androidClientId: '675335972613-2uhgnpnp0oh0b9s1f3if61ptnb180t5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFYea0bkcGUaGa8_TOD7ACKTio1QJAI0',
    appId: '1:675335972613:ios:47505aa129d4cbd33ab96c',
    messagingSenderId: '675335972613',
    projectId: 'avs-control',
    databaseURL: 'https://avs-control-default-rtdb.firebaseio.com',
    storageBucket: 'avs-control.appspot.com',
    androidClientId: '675335972613-2uhgnpnp0oh0b9s1f3if61ptnb180t5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLO95ytkCv6LYvokTZL4x9a-6weUAIPMM',
    appId: '1:675335972613:web:d2a7828cfad537db3ab96c',
    messagingSenderId: '675335972613',
    projectId: 'avs-control',
    authDomain: 'avs-control.firebaseapp.com',
    databaseURL: 'https://avs-control-default-rtdb.firebaseio.com',
    storageBucket: 'avs-control.appspot.com',
    measurementId: 'G-VX8V8TKV52',
  );

}