// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_F1rtL8YZagzxuv3Sxsi5afohkRa6bA',
    appId: '1:698490110406:web:2444c8be1a7eca3d9572c7',
    messagingSenderId: '698490110406',
    projectId: 'ecommerce-app-a34cf',
    authDomain: 'ecommerce-app-a34cf.firebaseapp.com',
    storageBucket: 'ecommerce-app-a34cf.appspot.com',
    measurementId: 'G-R46TWPCBN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA78s_KQczGUMKFvIuSjbukbFftHB_ANyo',
    appId: '1:698490110406:android:269136d016cd09039572c7',
    messagingSenderId: '698490110406',
    projectId: 'ecommerce-app-a34cf',
    storageBucket: 'ecommerce-app-a34cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbllImzI8bJFJiImovBYtgzkPsLceMp8c',
    appId: '1:698490110406:ios:4c46ceabf26c1d409572c7',
    messagingSenderId: '698490110406',
    projectId: 'ecommerce-app-a34cf',
    storageBucket: 'ecommerce-app-a34cf.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbllImzI8bJFJiImovBYtgzkPsLceMp8c',
    appId: '1:698490110406:ios:4c46ceabf26c1d409572c7',
    messagingSenderId: '698490110406',
    projectId: 'ecommerce-app-a34cf',
    storageBucket: 'ecommerce-app-a34cf.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb_F1rtL8YZagzxuv3Sxsi5afohkRa6bA',
    appId: '1:698490110406:web:bcc1fb4a3fff2c3c9572c7',
    messagingSenderId: '698490110406',
    projectId: 'ecommerce-app-a34cf',
    authDomain: 'ecommerce-app-a34cf.firebaseapp.com',
    storageBucket: 'ecommerce-app-a34cf.appspot.com',
    measurementId: 'G-H57LEK286B',
  );
}
